version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    pre_build:
      - echo nothing to do
  build:
    commands:
      - sam build
      - sam package --s3-bucket helloworldfromgithub --output-template-file outputtemplate.yaml
  post_build:
    commands:
      - echo Build started on `date`
artifacts:
  files:
    - outputtemplate.yaml